%YAML 1.1
---
$schema: 'http://json-schema.org/draft-07/schema#'
$id: 'executor_config.yaml'
type: object
additionalProperties: false
required:
  - version
  - executor
properties:
  version:
    type: integer
  executor:
    type: object
